services:
  api:
    image: ${DOCKER_REGISTRY-}eventsourcing
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      database:
        condition: service_healthy
  
  database:
    image: postgres:latest
    container_name: database
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  identity.database:
    image: postgres:latest
    container_name: identity.database
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5